name: Apollo Server Plugin CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  # Run every Monday at 9AM PST (16 UTC)
  - cron: '0 16 * * 1'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Linting
      run: npm run lint

  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run unit
      - name: Post Unit Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/unit/
          files: lcov.info
          flags: unit-tests-${{ matrix.node-version }}


  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Integration Tests
        run: npm run integration
      - name: Post Integration Test Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/integration/
          files: lcov.info
          flags: integration-tests-${{ matrix.node-version }}

  versioned:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Versioned Tests (npm v6 / Node 14)
      if: ${{ matrix.node-version == '14.x' }}
      run: npm run versioned:npm6
    - name: Run Versioned Tests (npm v7+ / Node 16+)
      if: ${{ matrix.node-version != '14.x' }}
      run: npm run versioned:npm7
    - name: Post Versioned Test Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/versioned/
        files: lcov.info
        flags: versioned-tests-${{ matrix.node-version }}

